name: Notify issues slack

on:
  issues:
    types:
      - opened

jobs:
  notify-issues-slack:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    steps:
      - name: Post Slack messages
        uses: abinoda/slack-action@v1.0.9
        with:
          args: '{\"channel\":\"C06DTQCL4CT\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Nuova Issue\n*<${{ github.event.issue.html_url }}|Vai alla issue>*\"}},{\"type\":\"section\",\"fields\":[{\"type\":\"mrkdwn\",\"text\":\"*Autor:*\n@${{ github.actor }}\"},{\"type\":\"mrkdwn\",\"text\":\"*Repository:*\n${{ github.repository }}\"},{\"type\":\"mrkdwn\",\"text\":\"*PR title:*\n${{ github.event.issue.title }}\"}]}]}'
