name: Sync submodule

on:
  push:
    branches:
      - main

jobs:
  sync-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Aggiunta variabili ambiente
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "${{ secrets.SC_GIT_USERNAME }}"
          git config user.email "${{ secrets.SC_GH_EMAIL }}"
          ls -la
          ls -la ./actions_submodule/
          
      - name: Aggiornamento submodule
        run: |
          cd ..
          git clone git@github.com:unipr-org/org-actions.git
          cd ./org-actions/
          ls -la ./
          ls -la ./shared_actions/
          cd ..
          
      - name: Copia file da actions_submodule
        run: |
          cp -r ./org-actions/shared_actions/* ./org-wiki/.github/workflows/
          git add ./.github/workflows/
          git commit -m "@sync_submodule_action: Copia automatica di file da ./org-actions/shared_actions/* a ./.github/workflows/"
      
      - name: Push submodule
        run: |
          git push origin main
      
