name: Sync submodule

on:
  push:
    branches:
      - main

jobs:
  sync-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Aggiornamento submodule
        run: |
          git submodule update --recursive --remote
          git add actions_submodule
          git commit -m "Aggiornamento automatico actions_submodule"
        
      - name: Copia file da actions_submodel
        run: |
          cp -r ./actions_submodule/.github/workflows/* ./.github/workflows/
          git add ./.github/workflows/
          git commit -m "Copia automatica di file da actions_submodule a ./.github/workflows/"
          git push
      
